/* Página de detalhe do imóvel (galeria, comprar, WhatsApp) e navegação por endereço (#imovel/RM-001). */
const home=document.querySelector('main'),det=document.createElement('main');det.id='detail';det.hidden=true;home.after(det);
const TX={Apartamento:'Planta bem distribuída, ambientes integrados e boa iluminação natural, em prédio com infraestrutura completa.',Cobertura:'Terraço privativo com área de lazer e vista ampla, ideal para receber família e amigos com conforto e exclusividade.',Casa:'Espaço generoso para a família, com integração entre sala e área externa, jardim e privacidade.',Comercial:'Sala em localização estratégica, com boa circulação de clientes e fácil acesso ao transporte.'};
const VB=['0 0 1600 900','400 150 800 450','800 300 600 338','300 400 600 338'],VL=['Fachada','Detalhe da fachada','Ambientes','Entrada'];
let detCur='',lastY=0,slideTimer=0,slideIndex=0;
const stopGallerySlideshow=()=>{if(slideTimer){clearInterval(slideTimer);slideTimer=0}};
const fe=(k,n,l)=>'<div class="fe">'+IC[k]+'<b>'+n+'</b><span>'+l+'</span></div>';
const waIc='<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M12 2a10 10 0 0 0-8.6 15.1L2 22l5-1.3A10 10 0 1 0 12 2zm5.2 14.2c-.2.6-1.3 1.2-1.8 1.2-.5.1-1 .2-3.3-.7-2.8-1.2-4.6-4-4.7-4.2-.1-.2-1.1-1.5-1.1-2.8s.7-2 1-2.3c.2-.3.5-.3.7-.3h.5c.2 0 .4 0 .6.5l.8 2c.1.2.1.4 0 .5l-.3.5-.4.4c-.1.2-.3.3-.1.6.2.3.8 1.3 1.7 2.1 1.2 1 2.1 1.3 2.4 1.5.3.1.5.1.6-.1l.9-1.1c.2-.3.4-.2.6-.1l1.9.9c.3.1.5.2.5.3.1.1.1.6-.1 1.2z"/></svg>';
const actions=(i,al)=>{if(i.st&&i.st!=='disp')return '<p class="soldmsg">Este imóvel já foi '+(i.st==='alugado'?'alugado':'vendido')+'. Volte à lista para ver os imóveis disponíveis.</p>';const t='Olá! Tenho interesse em '+(al?'alugar':'comprar')+' o imóvel '+i.cod+' – '+i.titulo+' ('+i.tipo+' em '+i.bairro+', '+i.cidade+', R$ '+F(i.valor)+(al?'/mês':'')+'). Pode me passar mais informações?';return '<button type="button" class="buy" id="dBuy">'+(al?'Alugar':'Comprar')+'</button><a class="wa" id="dWa" target="_blank" rel="noopener" href="'+waLink(t)+'">'+waIc+(al?'Alugar':'Comprar')+' pelo WhatsApp</a><p class="note">Um corretor da ROMA entra em contato para agendar a visita e tirar suas dúvidas.</p>'};
function showDet(cod){
 const i=IM.find(x=>x.cod===cod&&!x.arquivado);if(!i)return showHome();
 stopGallerySlideshow();document.body.classList.remove('gallery-open');
 const al=i.fin==='aluguel';if(!detCur)lastY=scrollY;detCur=cod;
 const photos=Array.isArray(i.fotos)?i.fotos.filter(url=>typeof url==='string'&&url):[],videoId=youtubeVideoId(i.video),items=(photos.length?photos:videoId?[]:VB.map(v=>svgUrl(i.art,v))).map(url=>({type:'image',url}));
 det.innerHTML='<section class="det"><div class="wrap"><button type="button" class="back" id="dBack">← Voltar aos imóveis</button><div class="dgrid"><div class="gal"><div class="gmain" id="gmain" role="button" tabindex="0" aria-label="Abrir imagem ampliada"></div><div class="gthumbs"><button type="button" class="gth-arrow" id="gPrev" aria-label="Ver imagens anteriores">‹</button><div class="gth" id="gth" aria-label="Imagens do imóvel"></div><button type="button" class="gth-arrow" id="gNext" aria-label="Ver próximas imagens">›</button></div></div>'
 +'<aside class="dinfo"><div class="drow"><span class="tag2">'+(i.st==='vendido'?'Vendido':i.st==='alugado'?'Alugado':al?'Aluguel':'Venda')+'</span><span class="cod">Cód. '+i.cod+'</span></div><h2>'+i.titulo+'</h2><p class="loc">'+i.tipo+' · '+i.bairro+', '+i.cidade+'</p><div class="dprice">R$ '+F(i.valor)+(al?'<small>/mês</small>':'')+'</div>'+actions(i,al)+'</aside></div>'
 +'<div class="dtext"><h3>Sobre o imóvel</h3><p>'+desc(i)+' '+(i.texto||TX[i.tipo]||'')+' Localizado em '+i.bairro+', '+i.cidade+'.</p><h3>Características</h3><div class="feats">'+(i.q?fe('bed',i.q,i.q===1?'Quarto':'Quartos'):'')+(i.s?fe('suite',i.s,i.s===1?'Suíte':'Suítes'):'')+fe('bath',i.b,i.b===1?'Banheiro':'Banheiros')+fe('car',i.v,i.v===1?'Vaga de garagem':'Vagas de garagem')+fe('area',F(i.area)+' m²','Área útil')+'</div>'
 +'<h3>Ficha técnica</h3><dl class="spec">'+[['Tipo',i.tipo],['Finalidade',al?'Aluguel':'Venda'],['Cidade',i.cidade],['Bairro',i.bairro],['Área útil',F(i.area)+' m²'],['Código',i.cod],[al?'Aluguel mensal':'Valor','R$ '+F(i.valor)]].map(r=>'<div><dt>'+r[0]+'</dt><dd>'+r[1]+'</dd></div>').join('')+'</dl>'+(!photos.length&&!videoId?'<p class="note">Imagens ilustrativas usadas enquanto este imóvel não possui fotos cadastradas.</p>':'')+'</div></div></section><div class="gallery-lightbox" id="galleryLightbox" role="dialog" aria-modal="true" aria-label="Imagem ampliada do imóvel" hidden><button type="button" class="gallery-close" id="galleryClose" aria-label="Fechar imagem ampliada">×</button><button type="button" class="gth-arrow gallery-arrow" id="galleryPrev" aria-label="Imagem anterior">‹</button><div class="gallery-lightbox-stage" id="galleryStage"></div><button type="button" class="gth-arrow gallery-arrow" id="galleryNext" aria-label="Próxima imagem">›</button><span class="gallery-counter" id="galleryCounter" aria-live="polite"></span></div>';
 if(i.video&&!videoId)console.warn('Link do YouTube inválido no imóvel '+i.cod+'.');
 if(videoId)items.push({type:'video',id:videoId});
 const gm=$('gmain'),gt=$('gth'),lightbox=$('galleryLightbox'),stage=$('galleryStage');slideIndex=0;
 const renderLightbox=()=>{const item=items[slideIndex];stage.replaceChildren();if(item.type==='video'){const iframe=document.createElement('iframe');iframe.src='https://www.youtube-nocookie.com/embed/'+item.id+'?autoplay=1&rel=0&vq=hd2160';iframe.title='Vídeo do imóvel '+i.cod;iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;stage.appendChild(iframe)}else{const image=document.createElement('img');image.src=item.url;image.alt='Imagem '+(slideIndex+1)+' do imóvel '+i.cod;stage.appendChild(image)}$('galleryCounter').textContent=(slideIndex+1)+' / '+items.length};
 const openLightbox=()=>{stopGallerySlideshow();renderLightbox();lightbox.hidden=false;document.body.classList.add('gallery-open');$('galleryClose').focus()};
 const closeLightbox=()=>{if(lightbox.hidden)return;lightbox.hidden=true;stage.replaceChildren();document.body.classList.remove('gallery-open');gm.focus()};
 const moveLightbox=direction=>{if(lightbox.hidden)return;pick((slideIndex+direction+items.length)%items.length);renderLightbox()};
 const pick=k=>{const item=items[k];if(!item)return;slideIndex=k;gm.replaceChildren();if(item.type==='video'){gm.style.backgroundImage='url("https://img.youtube.com/vi/'+item.id+'/hqdefault.jpg")';gm.innerHTML='<span class="gmain-play" aria-hidden="true">▶</span>';gm.setAttribute('aria-label','Reproduzir vídeo do imóvel '+i.cod+' em tela ampliada');}else{gm.style.backgroundImage='url("'+item.url+'")';gm.setAttribute('aria-label','Abrir imagem ampliada: '+(VL[k]||'Foto '+(k+1)));}gm.setAttribute('tabindex','0');gm.setAttribute('role','button');[...gt.children].forEach((b,j)=>b.classList.toggle('on',j===k));const thumb=gt.children[k];if(thumb)thumb.scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'});if(!lightbox.hidden)renderLightbox()};
 items.forEach((item,k)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',item.type==='video'?'Reproduzir vídeo do imóvel':VL[k]||'Foto '+(k+1));b.style.backgroundImage=item.type==='video'?'url("https://img.youtube.com/vi/'+item.id+'/mqdefault.jpg")':'url("'+item.url+'")';if(item.type==='video'){b.classList.add('video-thumb');b.innerHTML='<span aria-hidden="true">▶</span>'}b.onclick=()=>{stopGallerySlideshow();pick(k)};gt.appendChild(b)});pick(0);
 const scrollThumbs=direction=>gt.scrollBy({left:direction*Math.max(gt.clientWidth*.8,160),behavior:'smooth'});
 $('gPrev').onclick=()=>{stopGallerySlideshow();scrollThumbs(-1)};$('gNext').onclick=()=>{stopGallerySlideshow();scrollThumbs(1)};
 gm.addEventListener('click',openLightbox);gm.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&gm.getAttribute('role')==='button'){e.preventDefault();openLightbox()}});
 $('galleryClose').onclick=closeLightbox;$('galleryPrev').onclick=()=>moveLightbox(-1);$('galleryNext').onclick=()=>moveLightbox(1);
 lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});
 lightbox.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();closeLightbox()}else if(e.key==='ArrowLeft'){e.preventDefault();moveLightbox(-1)}else if(e.key==='ArrowRight'){e.preventDefault();moveLightbox(1)}});
 if(items.length>1)slideTimer=setInterval(()=>pick((slideIndex+1)%items.length),5000);
 $('dBack').onclick=()=>{showHome();try{location.hash='#imoveis'}catch(e){}};
 if($('dBuy'))$('dBuy').onclick=()=>{openModal('comprar',false);const p=$('p-comprar'),x=p.querySelectorAll('input:not([type])'),sl=p.querySelector('select'),ta=p.querySelector('textarea');
  sl.value=i.tipo;x[0].value=i.cidade;x[1].value=i.bairro;ta.value='Tenho interesse '+(al?'em alugar':'em comprar')+' o imóvel '+i.cod+' – '+i.titulo+' (R$ '+F(i.valor)+(al?'/mês':'')+').';
  $('mtitle').textContent=al?'Solicitação de aluguel':'Solicitação de compra'};
 home.hidden=true;det.hidden=false;scrollTo(0,0);
}
function showHome(){stopGallerySlideshow();if(det.hidden)return;const lightbox=$('galleryLightbox');if(lightbox&&!lightbox.hidden){lightbox.hidden=true;$('galleryStage').replaceChildren();document.body.classList.remove('gallery-open')}det.hidden=true;home.hidden=false;detCur='';scrollTo(0,lastY)}
function route(){const m=location.hash.match(/^#imovel\/(.+)$/);if(m){const c=decodeURIComponent(m[1]);if(c!==detCur)showDet(c)}else if(!det.hidden){showHome();const el=location.hash.length>1&&document.getElementById(location.hash.slice(1));if(el)el.scrollIntoView()}}
addEventListener('hashchange',route);
$('grid').addEventListener('click',e=>{const b=e.target.closest('.more');if(!b)return;showDet(b.dataset.cod);try{location.hash='#imovel/'+b.dataset.cod}catch(x){}});
document.querySelectorAll('header a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href').slice(1);if(det.hidden||id==='contato')return;e.preventDefault();showHome();const el=$(id);if(el)el.scrollIntoView()}));
