/* Ações dos botões (clique). */
document.addEventListener('click',async e=>{const b=e.target.closest('[data-p],[data-a]');if(!b)return;const a=b.dataset.a,id=b.dataset.id;
 const session=SS();if(session&&session.via!=='senha'&&!me()){render();return}
 if(imageProcessing&&(b.dataset.p||['new','edit','save','cancel','rmph'].includes(a)))return toast('Aguarde o processamento das imagens antes de continuar.');
 if(designSlidesProcessing&&(b.dataset.p||a==='removeDesignSlide'||a==='saveDesignSlides'))return toast('Aguarde o processamento das imagens do carrossel.');
 if(['delu','deli','delm','approve-msg-delete','reject-msg-delete','release-msg','savecfg','savewa','savesso','exp','promo','tadd','tstatus','unarchive'].includes(a)&&!isAdm())return toast('Sem permissão para esta ação.');
 if(b.dataset.p){page=b.dataset.p;if(page==='mine')flt.mine='atend';ed=null;edAdvertiserMessageId=null;hl=null;return render()}
 if(a==='vmsg'){e.preventDefault();const m=MS().find(x=>String(x.id)===String(id));page=m&&m.atendimento?'mine':'notif';hl=id;flt.mine='';return render()}
 if(a==='assume-msg'){const all=MS(),m=all.find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');if(m.atendimento)return toast('Esta mensagem já foi assumida por '+(m.atendimento.nome||'outro atendente')+'.');const u=me()||{};m.atendimento={id:currentUserKey(),email:u.email||'',nome:u.nome||u.email||'Atendente',em:new Date().toISOString()};m.status='atend';if(!DB.set('roma_msgs',all))return toast('Não foi possível salvar a atribuição.');toast('Mensagem adicionada à sua fila.');page='mine';flt.mine='atend';return render()}
 if(a==='whatsapp-link'){const m=MS().find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');window.open(waTo(fv(m,'WhatsApp'),'Olá '+(fv(m,'Nome completo')||'')+'! Recebemos sua mensagem e estamos entrando em contato.'),'_blank','noopener');return}
 if(a==='release-msg'){const all=MS(),m=all.find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');delete m.atendimento;if(m.status==='atend')m.status='nova';if(!DB.set('roma_msgs',all))return toast('Não foi possível liberar o atendimento.');toast('Mensagem devolvida à fila geral.');return render()}
 if(a==='msg-sale'){const m=MS().find(x=>String(x.id)===String(id));if(!m||(!isAdm()&&messageOwnerId(m)!==currentUserKey()))return toast('Esta mensagem não está na sua fila.');return openMessageSale(id)}
 if(a==='msg-withdraw'){const m=MS().find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');if(!isAdm()&&messageOwnerId(m)!==currentUserKey())return toast('Esta mensagem está na fila de outro colaborador.');if(m.desistencia)return toast('A desistência desta mensagem já foi registrada.');if(messageHasDeal(m))return toast('Esta mensagem já está vinculada a uma negociação.');return openMessageWithdraw(id)}
 if(a==='submit-msg-withdraw'){const all=MS(),m=all.find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');if(!isAdm()&&messageOwnerId(m)!==currentUserKey())return toast('Esta mensagem está na fila de outro colaborador.');if(m.desistencia)return toast('A desistência desta mensagem já foi registrada.');if(messageHasDeal(m))return toast('Esta mensagem já está vinculada a uma negociação.');const u=me()||{};m.desistencia={por:u.nome||u.email||'Atendente',em:new Date().toISOString(),motivo:$('msgWithdrawReason').value.trim()};m.status='ok';if(!DB.set('roma_msgs',all))return toast('Não foi possível registrar a desistência.');$('msgWithdrawDialog').remove();page='mine';flt.mine='semneg';toast('Solicitação encerrada sem negociação.');return render()}
 if(a==='request-msg-delete'){if(isAdm())return toast('Administradores podem excluir a mensagem diretamente.');const m=MS().find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');if(messageHasDeal(m))return toast('Não é possível excluir uma mensagem vinculada a uma venda.');if(messageOwnerId(m)!==currentUserKey())return toast('Esta mensagem está na fila de outro colaborador.');if(pendingMessageDeletions().some(n=>n.messageId===String(id)))return toast('Já existe uma solicitação de exclusão pendente.');return openMessageDeleteRequest(id)}
 if(a==='close-msg-dialog'){document.querySelectorAll('#msgDeleteDialog,#msgSaleDialog,#msgWithdrawDialog').forEach(o=>o.remove());return}
 if(a==='submit-msg-delete'){if(isAdm())return toast('Administradores podem excluir a mensagem diretamente.');const reason=$('msgDeleteReason').value.trim();if(!reason)return toast('Informe o motivo da exclusão.');const m=MS().find(x=>String(x.id)===String(id));if(!m)return toast('Mensagem não encontrada.');if(messageHasDeal(m))return toast('Não é possível excluir uma mensagem vinculada a uma venda.');if(messageOwnerId(m)!==currentUserKey())return toast('Esta mensagem está na fila de outro colaborador.');if(pendingMessageDeletions().some(n=>n.messageId===String(id)))return toast('Já existe uma solicitação de exclusão pendente.');const u=me()||{},all=messageDeletions();all.push({id:Date.now()+'-'+Math.random().toString(36).slice(2),messageId:String(id),cliente:fv(m,'Nome completo'),motivo:reason,por:u.nome||u.email||'Colaborador',nome:u.nome||u.email||'Colaborador',email:u.email||'',em:new Date().toISOString(),status:'pendente'});if(!DB.set('roma_msg_notificacoes',all))return toast('Não foi possível enviar a solicitação.');document.getElementById('msgDeleteDialog').remove();toast('Solicitação enviada aos administradores.');return render()}
 if(a==='approve-msg-delete'||a==='reject-msg-delete'){const requests=messageDeletions(),request=requests.find(n=>String(n.id)===String(id)&&n.status==='pendente');if(!request)return toast('Solicitação pendente não encontrada.');const all=MS(),u=me()||{},linked=all.find(m=>String(m.id)===request.messageId);if(a==='approve-msg-delete'&&linked&&messageHasDeal(linked)){request.status='recusada';request.decidedBy=u.nome||u.email||'Administrador';request.decidedAt=new Date().toISOString();if(!DB.set('roma_msg_notificacoes',requests))return toast('Não foi possível atualizar a solicitação.');toast('A mensagem foi mantida porque já está vinculada a uma venda.');return render()}request.status=a==='approve-msg-delete'?'aprovada':'recusada';request.decidedBy=u.nome||u.email||'Administrador';request.decidedAt=new Date().toISOString();if(!DB.set('roma_msg_notificacoes',requests))return toast('Não foi possível atualizar a solicitação.');if(a==='approve-msg-delete'){if(!DB.set('roma_msgs',all.filter(m=>String(m.id)!==request.messageId))){request.status='pendente';delete request.decidedBy;delete request.decidedAt;DB.set('roma_msg_notificacoes',requests);return toast('Não foi possível excluir a mensagem.');}toast('Exclusão aprovada; mensagem removida.')}else toast('Solicitação recusada.');return render()}
 if(a==='submit-msg-sale')return completeMessageSale(id);
 if(a==='menu'){document.querySelector('.shell').classList.toggle('open');return}
 if(a==='sp'){const p=$('p');p.type=p.type==='password'?'text':'password';b.textContent=p.type==='password'?'Mostrar':'Ocultar';return}
 if(a==='out'){try{sessionStorage.removeItem('roma_sess')}catch(x){}return render()}
 if(a==='new'){ed=blank();edOwner={nome:'',cpf:'',rg:'',telefone:'',email:''};edAdvertiserMessageId=null;imageProgress={visible:false,percent:0,label:''};return render()}
 if(a==='edit'){ed=JSON.parse(JSON.stringify(IM.find(i=>i.cod===id)));edAdvertiserMessageId=null;if(ed){if(!Array.isArray(ed.fotos))ed.fotos=[];if(typeof ed.video!=='string')ed.video='';edOwner=Object.assign({nome:'',cpf:'',rg:'',telefone:'',email:''},advertiserFor(id))}imageProgress={visible:false,percent:0,label:''};return render()}
 if(a==='cancel'){ed=null;edOwner={nome:'',cpf:'',rg:'',telefone:'',email:''};edAdvertiserMessageId=null;imageProgress={visible:false,percent:0,label:''};return render()}
 if(a==='rmph'){collect();ed.fotos.splice(+id,1);return render()}
 if(a==='save'){if(imageProcessing)return toast('Aguarde o processamento das imagens antes de salvar.');collect();if(!ed.titulo||!ed.cidade||!ed.valor)return toast('Preencha título, cidade e valor.');if(!edOwner.nome||!edOwner.cpf||!edOwner.rg||!edOwner.telefone||!edOwner.email)return toast('Preencha todos os dados obrigatórios do cliente anunciante.');if(!validCPF(edOwner.cpf))return toast('Informe um CPF válido.');if(![10,11].includes(edOwner.telefone.replace(/\D/g,'').length))return toast('Informe um telefone válido com DDD.');if(!$('o_email').checkValidity())return toast('Informe um e-mail válido.');if((ed.fotos||[]).length>14)return toast('O limite é de 14 fotos por imóvel.');if(ed.video&&!youtubeVideoId(ed.video))return toast('Informe um link válido de vídeo do YouTube.');const linkedMessageId=edAdvertiserMessageId,allMessages=MS(),advertiserMessage=linkedMessageId&&allMessages.find(message=>String(message.id)===String(linkedMessageId));if(linkedMessageId&&!advertiserMessage)return toast('A mensagem de anúncio vinculada não foi encontrada. Atualize a tela e tente novamente.');const cod=ed.cod||nextCod(),previous=IM,previousAdvertisers=ANUNCIANTES;IM=ed.cod?IM.map(i=>i.cod===cod?ed:i):[Object.assign({},ed,{cod}),...IM];if(savePropertyAndAdvertiser(cod)){if(advertiserMessage){advertiserMessage.status='ok';advertiserMessage.anuncioCriado={cod,nome:ed.titulo,em:new Date().toISOString()};if(!DB.set('roma_msgs',allMessages)){IM=previous;ANUNCIANTES=previousAdvertisers;if(!DB.set('roma_anunciantes',previousAdvertisers))console.error('Não foi possível reverter os dados do anunciante após falha ao concluir a mensagem.');if(!saveIM())console.error('Não foi possível reverter o imóvel após falha ao concluir a mensagem.');return toast('Não foi possível concluir a mensagem de anúncio; o cadastro do imóvel foi revertido.')}}ed=null;edOwner={nome:'',cpf:'',rg:'',telefone:'',email:''};edAdvertiserMessageId=null;imageProgress={visible:false,percent:0,label:''};toast(advertiserMessage?'Imóvel salvo e anúncio marcado como criado.':'Imóvel salvo.');page=advertiserMessage?'mine':page;if(advertiserMessage){flt.mine='ok';hl=linkedMessageId}render()}else IM=previous;return}
 if(a==='archive'){const reason=prompt('Informe o motivo para arquivar este imóvel:');if(reason===null)return;if(!reason.trim())return toast('Informe o motivo do arquivamento.');const i=IM.find(x=>x.cod===id);if(!i)return toast('Imóvel não encontrado.');i.arquivado={motivo:reason.trim(),em:new Date().toISOString(),por:(me()||{}).nome||'Colaborador'};if(saveIM()){toast('Imóvel arquivado.');render()}return}
 if(a==='unarchive'){const i=IM.find(x=>x.cod===id);if(!i||!i.arquivado)return;if(i.st!=='disp'&&!confirm('Este imóvel está '+(i.st==='alugado'?'alugado':'vendido')+'. Reativá-lo também removerá o registro do negócio. Continuar?'))return;i.arquivado=null;if(i.st!=='disp'){i.st='disp';delete i.fech}if(saveIM()){toast('Imóvel reativado.');render()}return}
 if(a==='deli'){if(!isAdm())return toast('Sem permissão para excluir imóveis.');if(confirm('Excluir este imóvel?')){if(deletePropertyAndAdvertiser(id))render()}return}
 if(a==='deal')return openDeal(id);
 if(a==='dcancel')return closeDeal();
 if(a==='dsave'){
  const i=IM.find(x=>x.cod===id);if(!i)return toast('Imóvel não encontrado.');
  const previous=i.fech||{};if(i.fech&&!canEditDeal(previous))return toast(dealEditExpired(previous)?'O prazo de 7 dias para editar este negócio expirou.':'Somente o colaborador responsável ou um administrador pode editar este negócio.');
  const al=i.fin==='aluguel',client=al?{nome:$('d_cli').value.trim(),telefone:$('d_tel').value.trim(),cpf:previous.cpf||'',rg:previous.rg||'',email:previous.email||''}:{nome:$('d_clientName').value.trim(),telefone:$('d_tel').value.trim(),cpf:$('d_cpf').value.replace(/\D/g,''),rg:$('d_rg').value.trim(),email:$('d_email').value.trim().toLowerCase()},d=$('d_data').value;
  if(!client.nome||!d)return toast('Informe o cliente e a data.');
  if(!al&&(!client.telefone||!client.cpf||!client.rg||!client.email))return toast('Preencha os dados pessoais obrigatórios do cliente.');
  if(!al&&!validCPF(client.cpf))return toast('Informe um CPF válido para o cliente.');
  if(!al&&![10,11].includes(client.telefone.replace(/\D/g,'').length))return toast('Informe um telefone válido com DDD para o cliente.');
  if(!al&&!$('d_email').checkValidity())return toast('Informe um e-mail válido para o cliente.');
  const ori=$('d_ori').value,mid=ori==='site'?$('d_msg').value:previous.msgId||'',selected=$('d_responsavel').value,legacyOwner=i.fech&&String(previous.porId||dealOwnerId(previous)).toLowerCase()===selected?{id:selected,nome:previous.por}:null,responsible=responsibleById(selected)||legacyOwner;
  if(!responsible)return toast('Selecione um responsável válido para o negócio.');
  const payment=al?previous.pagamento||'':$('d_payment').value;if(!al&&!payment)return toast('Selecione a forma de pagamento.');
  const financing=al?{entrada:0,parcelasQuantidade:0,parcelaValor:0}:financingValues('d');
  if(!al&&/financiamento/i.test(payment)&&(!Number.isInteger(financing.parcelasQuantidade)||financing.parcelasQuantidade<1||!financing.parcelaValor))return toast('Informe a quantidade e o valor das parcelas do financiamento.');
  const selectedDocuments=!al&&$('d_contractFiles')?[...$('d_contractFiles').files]:[];
  if(selectedDocuments.some(file=>file.size>1024*1024))return toast('Cada arquivo deve ter no máximo 1 MB.');
  if(selectedDocuments.some(file=>!saleDocumentTypes[saleDocumentExtension(file)]))return toast('Anexe somente arquivos PDF ou Word (DOC/DOCX).');
  let addedDocuments=[];try{addedDocuments=await Promise.all(selectedDocuments.map(readContractFile))}catch(error){return toast(error.message||'Não foi possível ler os arquivos selecionados.')}
  const documents=[...dealDocuments(previous),...addedDocuments];
  const oldClients=ADMIN_CLIENTS(),oldProperty=JSON.parse(JSON.stringify(i)),allMessages=MS(),oldMessages=JSON.parse(JSON.stringify(allMessages)),now=new Date().toISOString(),messageId=mid||'deal-'+i.cod+'-'+Date.now(),message=allMessages.find(item=>String(item.id)===String(messageId));
  if(mid&&!message)return toast('A mensagem vinculada não foi encontrada. Atualize a tela e tente novamente.');
  if(!al&&!updateAdminClient(client,i.cod))return;
  const fields=[{k:'Nome completo',v:client.nome},{k:'WhatsApp',v:client.telefone},{k:'CPF',v:client.cpf},{k:'RG',v:client.rg},{k:'E-mail',v:client.email},{k:'Imóvel',v:i.cod+' · '+i.titulo},{k:'Valor negociado',v:'R$ '+formatBRLValue(parseBRLInput($('d_val').value)||i.valor)},{k:'Forma de pagamento',v:payment}];
  if(message){message.atendimento={id:responsible.id,email:responsible.email||responsible.id,nome:responsible.nome,em:now};message.status='ok';if(!al){message.campos=fields;message.data=message.data||now;message.negocio={cod:i.cod,tipo:'venda',valor:parseBRLInput($('d_val').value)||i.valor,pagamento:payment,entrada:financing.entrada,parcelasQuantidade:financing.parcelasQuantidade,parcelaValor:financing.parcelaValor,em:now}}}
  else if(!al)allMessages.unshift({id:messageId,data:now,tipo:'comprar',status:'ok',campos:fields,atendimento:{id:responsible.id,email:responsible.email||responsible.id,nome:responsible.nome,em:now},negocio:{cod:i.cod,tipo:'venda',valor:parseBRLInput($('d_val').value)||i.valor,pagamento:payment,entrada:financing.entrada,parcelasQuantidade:financing.parcelasQuantidade,parcelaValor:financing.parcelaValor,em:now}});
  if((!al||message)&&!DB.set('roma_msgs',allMessages)){if(!al&&!DB.set(ADMIN_CLIENTS_KEY,oldClients))console.error('Não foi possível reverter os dados do cliente após falha ao registrar a mensagem de conclusão.');return toast('Não foi possível enviar o negócio para Meus clientes.')}
  i.st=al?'alugado':'vendido';i.arquivado=null;i.fech={...(al?{cliente:client.nome,tel:client.telefone}:{}),origem:ori,msgId:al?mid:messageId,data:d,registradoEm:previous.registradoEm||now,valor:parseBRLInput($('d_val').value)||i.valor,pagamento:payment,entrada:financing.entrada,parcelasQuantidade:financing.parcelasQuantidade,parcelaValor:financing.parcelaValor,contratos:documents,contrato:documents[0]||null,obs:$('d_obs').value.trim(),por:responsible.nome,porId:responsible.id};
  if(!saveIM()){IM[IM.indexOf(i)]=oldProperty;if((!al||message)&&!DB.set('roma_msgs',oldMessages))console.error('Não foi possível reverter a mensagem após falha ao salvar o negócio.');if(!al&&!DB.set(ADMIN_CLIENTS_KEY,oldClients))console.error('Não foi possível reverter os dados pessoais do cliente após falha ao salvar a negociação.');return}
  closeDeal();if(!al){page='mine';flt.mine='ok';hl=messageId}toast('Negócio registrado.'+(al?'':' e enviado para Meus clientes como concluído.'));render();return
 }
 if(a==='reopen'){if(confirm('Reabrir este imóvel? O registro do negócio será removido.')){const i=IM.find(x=>x.cod===id);i.st='disp';i.arquivado=null;delete i.fech;saveIM();render()}return}
 if(a==='reg'){const m=MS().find(x=>String(x.id)===id);if(!m)return toast('Mensagem não encontrada.');if(!isAdm()&&messageOwnerId(m)!==currentUserKey())return toast('Esta mensagem não está na sua fila.');const g=k=>fv(m,k);ed=Object.assign(blank(),m.tipo==='vender'?{fin:g('Finalidade')==='Alugar'?'aluguel':'venda',tipo:g('Tipo do imóvel')||'Casa',valor:parseBRLInput(g('Valor pretendido')),cep:g('CEP').replace(/\D/g,''),logradouro:g('Rua / logradouro'),numero:g('Número'),complemento:g('Complemento'),uf:g('UF'),cidade:g('Cidade'),bairro:g('Bairro'),area:num(g('Área')),q:num(g('Quartos')),v:num(g('Vagas')),texto:g('Descrição do imóvel')}:{tipo:g('Tipo de imóvel')||'Casa',cidade:g('Cidade'),bairro:g('Bairros de interesse'),valor:parseBRLInput(g('Valor máximo'))});edOwner={nome:g('Nome completo'),cpf:g('CPF'),rg:g('RG'),telefone:g('WhatsApp'),email:g('E-mail')||g('Email')};edAdvertiserMessageId=m.tipo==='vender'?String(m.id):null;page='imv';return render()}
 if(a==='delm'){if(!isAdm())return toast('Colaboradores precisam solicitar a exclusão ao administrador.');const message=MS().find(m=>String(m.id)===String(id));if(!message)return toast('Mensagem não encontrada.');if(messageHasDeal(message))return toast('Não é possível excluir uma mensagem vinculada a uma venda.');if(confirm('Excluir esta mensagem?')){if(!DB.set('roma_msgs',MS().filter(m=>String(m.id)!==id)))return toast('Não foi possível excluir a mensagem.');const requests=messageDeletions().filter(n=>n.messageId!==String(id)||n.status!=='pendente');if(!DB.set('roma_msg_notificacoes',requests))return toast('Mensagem excluída, mas não foi possível atualizar as notificações.');render()}return}
 if(a==='delu'){if(confirm('Excluir este cliente e os dados de anunciante associados?')){const client=clientDirectory().find(person=>person.id===id||person.email===id);if(client&&deleteClientByEmail(client.email))render()}return}
 if(a==='sg')return ssoGoogle();if(a==='sm')return ssoMs();
 if(a==='tadd'){const em=$('t_email').value.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(em))return toast('Informe um e-mail válido.');const all=TEAM();if(all.some(x=>x.email.toLowerCase()===em))return toast('Esse e-mail já está cadastrado.');all.push({email:em,nome:$('t_nome').value.trim(),papel:$('t_papel').value,ativo:true,criado:new Date().toISOString()});if(!DB.set('roma_team',all))return toast('Não foi possível adicionar a pessoa.');toast('Pessoa adicionada.');return render()}
 if(a==='tstatus'){const all=TEAM(),member=all.find(x=>x.email.toLowerCase()===String(id).toLowerCase());if(!member)return toast('Colaborador não encontrado.');if(member.ativo!==false&&!confirm('Inativar o acesso de '+(member.nome||member.email)+'? Os dados e históricos serão mantidos.'))return;member.ativo=member.ativo===false;if(!DB.set('roma_team',all))return toast('Não foi possível atualizar o acesso do colaborador.');toast(member.ativo?'Acesso ativado.':'Acesso inativado.');return render()}
 if(a==='promo'){const u=US().find(x=>x.email===id);if(u){const all=TEAM();if(!all.some(x=>x.email.toLowerCase()===id.toLowerCase())){all.push({email:u.email.toLowerCase(),nome:u.name,papel:'colab',ativo:true,criado:new Date().toISOString()});if(!DB.set('roma_team',all))return toast('Não foi possível adicionar o colaborador.');toast(u.name+' agora é colaborador(a).')}}return render()}
 if(a==='savesso'){CFG.googleId=$('c_gid').value.trim();CFG.msId=$('c_mid').value.trim();CFG.msTenant=$('c_mt').value.trim()||'common';DB.set('roma_cfg',CFG);toast('Login único salvo.');return}
 if(a==='savecfg'){if($('c_user').value.trim())CFG.usuario=$('c_user').value.trim();if($('c_senha').value)CFG.senha=$('c_senha').value;DB.set('roma_cfg',CFG);toast('Acesso atualizado.');return}
 if(a==='savewa'){const w=num($('c_whats').value);if(!w)return toast('Informe um número válido.');CFG.whats=String(w);DB.set('roma_cfg',CFG);toast('Número salvo.');return}
 if(a==='saveDesignSlides')return saveDesignSlides();
 if(a==='removeDesignSlide'){if(!isAdm())return toast('Sem permissão para alterar o carrossel.');return removeDesignSlide(+id)}
 if(a==='exp'||a==='csv'){let txt,nm,ty='application/json';if(a==='exp'){txt=JSON.stringify({imoveis:IM,anunciantes:ANUNCIANTES,mensagens:MS(),clientes:US(),clientesPainel:ADMIN_CLIENTS(),cfg:CFG},null,1);nm='roma-backup.json'}else{ty='text/csv';nm='roma-negocios.csv';txt='\ufeff'+['Data;Imóvel;Código;Tipo;Cliente;Contato;CPF;E-mail;Origem;Valor;Pagamento;Entrada;Parcelas;Valor parcela;Observações'].concat(negF().map(x=>{const client=dealClientForProperty(x.i.cod,x.f);return[dt(x.f.data),x.i.titulo,x.i.cod,x.t==='venda'?'Venda':'Locação',x.f.cliente||client.nome||'',x.f.tel||client.telefone||'',x.f.cpf||client.cpf||'',x.f.email||client.email||'',ORI[x.f.origem]||'',x.f.valor||x.i.valor,x.f.pagamento||'',x.f.entrada||'',x.f.parcelasQuantidade||'',x.f.parcelaValor||'',(x.f.obs||'').replace(/[;\n]/g,' ')].join(';')})).join('\n')}
  const l=document.createElement('a');l.href=URL.createObjectURL(new Blob([txt],{type:ty}));l.download=nm;l.click()}
});
