/* Página Painel: indicadores e resumos. */
const negs=()=>IM.filter(i=>['vendido','alugado'].includes(sOf(i))).map(i=>({i,f:i.fech||{},t:sOf(i)==='vendido'?'venda':'locacao'}));
function pgDash(){const ms=visibleMessages(),nv=MS().filter(m=>!m.atendimento),d=IM.filter(i=>sOf(i)==='disp').length,N=negs(),V=N.filter(x=>x.t==='venda'),L=N.filter(x=>x.t==='locacao'),sum=a=>a.reduce((s,x)=>s+(+x.f.valor||+x.i.valor||0),0);
 const o={site:0,whats:0,outro:0};N.forEach(x=>{if(o[x.f.origem]!=null)o[x.f.origem]++});const mx=Math.max(1,...Object.values(o));
 const K=(l,n,s,go)=>'<button class="kpi" data-p="'+go+'"><span>'+l+'</span><b>'+n+'</b><small>'+s+'</small></button>';
 return '<div class="kpis">'+K('Imóveis disponíveis',d,'de '+IM.length+' cadastrados','imv')+K('Vendidos',V.length,'R$ '+F(sum(V)),'neg')+K('Alugados',L.length,'R$ '+F(sum(L))+'/mês','neg')+K('Notificações',nv.length,ms.length+' mensagens visíveis','notif')+K('Clientes',clientDirectory().length,'compradores e anunciantes','cli')+'</div>'
 +'<div class="two"><div class="card"><h3>Origem dos negócios</h3>'+(N.length?'<div class="bars">'+Object.keys(ORI).map(k=>'<div><span>'+ORI[k]+'</span><em><u style="width:'+o[k]/mx*100+'%"></u></em><b>'+o[k]+'</b></div>').join('')+'</div>':'<p class="mut">Registre vendas e locações para ver de onde vêm seus negócios.</p>')+'</div>'
 +'<div class="card"><h3>Últimas mensagens</h3>'+(ms.length?ms.slice(0,5).map(m=>'<div class="row"><div><b>'+esc(fv(m,'Nome completo')||'Sem nome')+'</b><small>'+(m.tipo==='vender'?'Quer vender / alugar':'Quer comprar')+' · '+dtt(m.data)+(m.atendimento?' · Atendimento: '+esc(m.atendimento.nome||m.atendimento.email):'')+'</small></div>'+bd(m.status==='nova'?'nova':'',SM[m.status]||m.status||'Nova')+'</div>').join(''):'<p class="mut">Nenhuma mensagem ainda.</p>')+'</div></div>'
 +'<div class="card"><h3>Últimos negócios</h3>'+(N.length?N.sort((a,b)=>(b.f.data||'').localeCompare(a.f.data||'')).slice(0,5).map(x=>'<div class="row"><div><b>'+esc(x.i.titulo)+'</b><small>'+(x.t==='venda'?'Venda':'Locação')+' · '+esc(x.f.cliente||'cliente não informado')+' · '+dt(x.f.data)+'</small></div><div>'+bd(x.f.origem==='site'?'site':x.f.origem==='whats'?'whats':'',ORI[x.f.origem]||'—')+'</div></div>').join(''):'<p class="mut">Nenhum negócio registrado.</p>')+'</div>'}
