/* Página Imóveis: lista, filtros e formulário de cadastro/edição. */
const IMV_ICONS={
 add:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',
 edit:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16.5-.8 4.3 4.3-.8L19 8.5 15.5 5 4 16.5Z"/><path d="m13.8 6.7 3.5 3.5"/></svg>',
 deal:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 10 9-7 9 7v10H3zM9 20v-6h6v6"/><path d="M16.5 4.5h3v3"/></svg>',
 money:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M16 8.5c-.8-.7-1.8-1-3-1-1.7 0-3 .9-3 2.2 0 3.3 6 1.3 6 4.6 0 1.3-1.3 2.2-3 2.2-1.2 0-2.3-.4-3.2-1.2M12 5.5v13"/></svg>',
 reopen:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11a8 8 0 0 0-14.8-4L3 10"/><path d="M3 5v5h5M4 13a8 8 0 0 0 14.8 4L21 14"/><path d="M21 19v-5h-5"/></svg>',
 archive:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16v14H4zM3 3h18v4H3zM9 12h6"/><path d="m9 15 3 3 3-3"/></svg>',
 restore:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16v14H4zM3 3h18v4H3zM12 17v-7"/><path d="m9 13 3-3 3 3"/></svg>',
 trash:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M10 11v6m4-6v6M6 7l1 14h10l1-14M9 7V4h6v3"/></svg>'
};
const imvAction=(action,id,label,icon,primary=false,danger=false)=>'<button type="button" class="btn sm imv-action'+(icon==='money'?' imv-sale':'')+(primary?' primary':'')+(danger?' danger':'')+'" data-a="'+action+'" data-id="'+esc(id)+'" aria-label="'+esc(label)+'" title="'+esc(label)+'">'+IMV_ICONS[icon]+'</button>';
function pgImv(){if(ed)return formHtml();return '<div class="bar"><input id="q" placeholder="Buscar por título, código, bairro ou cidade" value="'+esc(flt.q)+'"><select id="fS"><option value="">Todas as situações</option>'+opt(Object.entries(STL),flt.s)+'<option value="arquivado"'+(flt.s==='arquivado'?' selected':'')+'>Arquivados</option></select><select id="fF"><option value="">Venda e aluguel</option>'+opt([['venda','Venda'],['aluguel','Aluguel']],flt.f)+'</select><button type="button" class="btn primary imv-action imv-new" data-a="new" aria-label="Novo imóvel" title="Novo imóvel">'+IMV_ICONS.add+'</button></div><div class="card tw" id="lst"></div>'}
function drawImv(){
 const q=flt.q.toLowerCase(),L=IM.filter(i=>(!q||(i.titulo+i.cod+i.bairro+i.cidade).toLowerCase().includes(q))&&(flt.s==='arquivado'?!!i.arquivado:!flt.s||(!i.arquivado&&sOf(i)===flt.s))&&(!flt.f||i.fin===flt.f));
 $('lst').innerHTML=L.length?'<table><thead><tr><th>Imóvel</th><th>Local</th><th>Finalidade</th><th class="r">Valor</th><th>Situação</th><th>Ações</th></tr></thead><tbody>'+L.map(i=>{
  const s=sOf(i),f=i.fech,a=i.arquivado,buyer=f?dealClientForProperty(i.cod,f):null;
  const actions=imvAction('edit',i.cod,'Editar imóvel','edit')+(a?(isAdm()?imvAction('unarchive',i.cod,'Reativar imóvel','restore'):''):(s==='disp'?imvAction('deal',i.cod,'Registrar '+(i.fin==='aluguel'?'locação':'venda'),'money',true):imvAction('deal',i.cod,'Ver negócio','deal')+imvAction('reopen',i.cod,'Reabrir imóvel','reopen')+imvAction('archive',i.cod,'Arquivar imóvel','archive')))+(!a&&s==='disp'?imvAction('archive',i.cod,'Arquivar imóvel','archive'):'')+(isAdm()?imvAction('deli',i.cod,'Excluir imóvel','trash',false,true):'');
  return '<tr><td><div class="who"><div class="th" data-k="'+i.cod+'"></div><div><b>'+esc(i.titulo)+'</b><small>'+i.cod+' · '+i.tipo+'</small></div></div></td><td>'+esc(i.bairro)+', '+esc(i.cidade)+'</td><td>'+(i.fin==='venda'?'Venda':'Aluguel')+'</td><td class="r">R$ '+F(i.valor)+(i.fin==='aluguel'?'/mês':'')+'</td><td>'+(a?bd('sold','Arquivado')+'<small class="cl">'+esc(a.motivo)+'</small>':sBd(i)+(f?'<small class="cl">'+esc(buyer.nome||buyer.name||f.cliente||'—')+' · '+(ORI[f.origem]||'—')+'</small>':''))+'</td><td><div class="act imv-actions">'+actions+'</div></td></tr>'
 }).join('')+'</tbody></table>':'<p class="empty">Nenhum imóvel encontrado.</p>';
 document.querySelectorAll('#lst .th[data-k]').forEach(el=>{const i=IM.find(x=>x.cod===el.dataset.k);if(i&&i.fotos&&i.fotos[0])el.style.backgroundImage='url("'+i.fotos[0]+'")'})
}
function formHtml(){const e=ed,o=edOwner,f=(id,l,v,t,x)=>'<label'+(x?' class="full"':'')+'>'+l+'<input id="e_'+id+'" '+(id==='valor'?'inputmode="decimal" data-mask="brl"':id==='cep'?'inputmode="numeric" data-mask="cep" data-cep-lookup data-cep-field="cep"':['logradouro','bairro','cidade','uf','complemento'].includes(id)?'data-cep-field="'+id+'"':'type="'+(t||'text')+'"')+' value="'+esc(id==='valor'?(v?formatBRLValue(v):''):v)+'"></label>';
 const progress=imageProgress.visible?'<div class="image-progress full" id="imageProgress"><label for="imageProgressBar" id="imageProgressText">'+esc(imageProgress.label)+'</label><progress id="imageProgressBar" max="100" value="'+imageProgress.percent+'"></progress></div>':'<div class="image-progress full" id="imageProgress" hidden><label for="imageProgressBar" id="imageProgressText"></label><progress id="imageProgressBar" max="100" value="0"></progress></div>';
 return '<div class="card"><h3>'+(e.cod?'Editar '+e.cod:'Novo imóvel')+'</h3><div class="g3">'+f('titulo','Título *',e.titulo,'text',1)+'<label>Finalidade<select id="e_fin">'+opt([['venda','Venda'],['aluguel','Aluguel']],e.fin)+'</select></label><label>Tipo<select id="e_tipo">'+opt(TIPOS.map(t=>[t,t]),e.tipo)+'</select></label>'+f('valor','Valor (R$) *',e.valor,'number')+f('cep','CEP',e.cep)+ '<p class="full" data-cep-status role="status" aria-live="polite"></p>'+f('logradouro','Rua / logradouro',e.logradouro,'text',1)+f('numero','Número',e.numero)+f('complemento','Complemento',e.complemento)+f('bairro','Bairro',e.bairro)+f('cidade','Cidade *',e.cidade)+f('uf','UF',e.uf)+f('area','Área (m²)',e.area,'number')+f('q','Quartos',e.q,'number')+f('s','Suítes',e.s,'number')+f('b','Banheiros',e.b,'number')+f('v','Vagas (carros)',e.v,'number')+'<label>Ilustração padrão<select id="e_art">'+opt(ARTS,e.art)+'</select></label><label class="full">Descrição<textarea id="e_texto" rows="4">'+esc(e.texto)+'</textarea></label><fieldset class="full advertiser-fields"><legend>Dados do cliente anunciante</legend><p class="mut">Dados para contato da equipe ROMA. Não são publicados na vitrine do site.</p><div class="g2"><label>Nome completo *<input id="o_nome" autocomplete="name" value="'+esc(o.nome)+'" required></label><label>CPF *<input id="o_cpf" data-mask="cpf" inputmode="numeric" autocomplete="off" value="'+esc(maskCPF(o.cpf))+'" required></label><label>RG *<input id="o_rg" autocomplete="off" value="'+esc(o.rg)+'" required></label><label>Telefone *<input id="o_telefone" data-mask="phone" inputmode="tel" autocomplete="tel" placeholder="(31) 9 9999-9999" value="'+esc(maskPhone(o.telefone))+'" required></label><label class="full">E-mail *<input id="o_email" type="email" autocomplete="email" value="'+esc(o.email)+'" required></label></div></fieldset><div class="full"><label>Fotos (até 14, opcional)<input type="file" id="e_fotos" accept="image/*" multiple'+(imageProcessing?' disabled':'')+'></label><small>'+(e.fotos||[]).length+' de 14 fotos adicionadas. Cada imagem tem limite final de 1,5 MB; as maiores são compactadas automaticamente priorizando a qualidade.</small>'+progress+'<div class="ph">'+(e.fotos||[]).map((u,k)=>'<div data-ph="'+k+'"><button type="button" data-a="rmph" data-id="'+k+'" aria-label="Remover foto"'+(imageProcessing?' disabled':'')+'>×</button></div>').join('')+'</div></div>'+f('video','Link do vídeo no YouTube (opcional)',e.video||'','url',1)+'</div><div class="acts"><button class="btn primary" data-a="save"'+(imageProcessing?' disabled':'')+'>Salvar imóvel</button><button class="btn" data-a="cancel"'+(imageProcessing?' disabled':'')+'>Cancelar</button></div></div>'}
const gv=id=>$('e_'+id).value,collect=()=>{if(!ed||!$('e_titulo'))return;Object.assign(ed,{titulo:gv('titulo').trim(),fin:gv('fin'),tipo:gv('tipo'),cep:gv('cep').replace(/\D/g,''),logradouro:gv('logradouro').trim(),numero:gv('numero').trim(),complemento:gv('complemento').trim(),uf:gv('uf').trim().toUpperCase(),cidade:gv('cidade').trim(),bairro:gv('bairro').trim(),area:+gv('area')||0,q:+gv('q')||0,s:+gv('s')||0,b:+gv('b')||0,v:+gv('v')||0,valor:parseBRLInput(gv('valor')),art:gv('art'),texto:gv('texto').trim(),video:gv('video').trim()});edOwner={nome:$('o_nome').value.trim(),cpf:$('o_cpf').value.replace(/\D/g,''),rg:$('o_rg').value.trim(),telefone:$('o_telefone').value.trim(),email:$('o_email').value.trim()}}
